kind: pipeline
pipeline:
  name: Push to Github
  identifier: Push_to_Github
  tags:
    docs: None
  stages:
    - stage:
        name: gh-push
        identifier: gh-push
        image: appleboy/drone-git-push
        settings:
        branch: master
        remote: git@github.com:avgra3/AudioConverter.git
        force: false
        commit: true
        ssh_key: ${{ secrets.get("github-key") }}
