kind: pipeline
pipeline:
  stages:
    - identifier: default
      name: default
      steps:
        - identifier: git-push
          name: git-push
          spec:
            connectorRef: account.docker
            image: appleboy/drone-git-push
            type: Plugin
            settings:
              branch: master
              remote: git@github.com:avgra3/AudioConverter.git
              force: false
              commit: true
              ssh_key: 2323

